package pnp

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/microsoft/typescript-go/internal/json"
	"github.com/microsoft/typescript-go/internal/repo"
	"github.com/microsoft/typescript-go/internal/tspath"
	"github.com/microsoft/typescript-go/internal/vfs/osvfs"
)

type TestSuite struct {
	Manifest json.Value `json:"manifest"`
	Tests    []TestCase `json:"tests"`
}

type TestCase struct {
	Imported string `json:"imported"`
	Importer string `json:"importer"`
	Expected string `json:"expected"`
	It       string `json:"it"`
}

func TestLoadPnPManifest(t *testing.T) {
	t.Parallel()
	cases := []struct {
		fileName string
		path     string
		msg      string
	}{
		{"pnp-yarn-v3.cjs", filepath.Join(repo.TestDataPath(), "fixtures", "pnp", "pnp-yarn-v3.cjs"), "Expected to load the .pnp.cjs file generated by Yarn 3"},
		{"pnp-yarn-v4.cjs", filepath.Join(repo.TestDataPath(), "fixtures", "pnp", "pnp-yarn-v4.cjs"), "Expected to load the .pnp.cjs file generated by Yarn 4"},
	}

	for _, tc := range cases {
		t.Run(tc.path, func(t *testing.T) {
			t.Parallel()

			fs := osvfs.FS()
			pnpDataString, err := extractPnpDataStringFromPath(fs, tc.path)
			if err != nil {
				t.Fatalf("failed to parse manifest: %v", err)
			}
			_, err = parseManifestFromData(pnpDataString, tspath.GetDirectoryPath(tc.path))
			if err != nil {
				t.Fatalf("failed to parse manifest: %v", err)
			}
		})
	}
}

func TestResolveUnqualified(t *testing.T) {
	t.Parallel()
	expectationsPath := filepath.Join(repo.TestDataPath(), "fixtures", "pnp", "test-expectations.json")

	content, err := os.ReadFile(expectationsPath)
	if err != nil {
		t.Fatalf("Assertion failed: Expected the expectations to be found: %v", err)
	}

	var suites []TestSuite
	if err = json.Unmarshal(content, &suites); err != nil {
		t.Fatalf("Assertion failed: Expected the expectations to be loaded: %v", err)
	}

	for si := range suites {
		testSuite := &suites[si]

		rawManifest := &testSuite.Manifest
		manifest, err := parseManifestFromData(rawManifest.String(), "/path/to/project")
		if err != nil {
			t.Fatalf("failed to init pnp manifest: %v", err)
		}

		for _, tc := range testSuite.Tests {
			parent := tspath.CombinePaths(tc.Importer, "fooo")
			pnpApi := &PnpApi{fs: osvfs.FS(), url: "/path/to/project/.pnp.cjs", manifest: manifest}

			t.Run(tc.It, func(t *testing.T) {
				t.Parallel()
				res, unqualifiedErr := pnpApi.ResolveToUnqualified(tc.Imported, parent)

				if tc.Expected == "error!" {
					if unqualifiedErr == nil {
						t.Fatalf("'%s': expected resolution to fail, got %q", tc.It, res)
					}
					return
				}

				if unqualifiedErr != nil {
					t.Fatalf("'%s': expected resolved path %q, got error: %v", tc.It, tc.Expected, unqualifiedErr.Message)
				}
				if res != tc.Expected {
					t.Fatalf("'%s': expected resolved path %q, got %q", tc.It, tc.Expected, res)
				}
			})
		}
	}
}

func TestIsExternalPackagePath(t *testing.T) {
	t.Parallel()

	manifest, err := parseManifestFromData(`{
		"dependencyTreeRoots": [{"name": "app", "reference": "workspace:app"}],
		"ignorePatternData": null,
		"enableTopLevelFallback": true,
		"fallbackPool": [["fallback", "workspace:fallback"]],
		"fallbackExclusionList": [],
		"packageRegistryData": [
			[null, [[null, {"packageLocation": "./", "packageDependencies": [], "linkType": "SOFT"}]]],
			["app", [["workspace:app", {"packageLocation": "./app/", "packageDependencies": [], "linkType": "SOFT"}]]],
			["fallback", [["workspace:fallback", {"packageLocation": "./fallback/", "packageDependencies": [], "linkType": "SOFT"}]]],
			["pkg", [
				["workspace:one", {"packageLocation": "./pkg-one/", "packageDependencies": [], "linkType": "SOFT"}],
				["workspace:two", {"packageLocation": "./pkg-two/", "packageDependencies": [], "linkType": "SOFT"}]
			]]
		]
	}`, "/repo")
	if err != nil {
		t.Fatalf("failed to parse manifest: %v", err)
	}
	pnpApi := &PnpApi{fs: osvfs.FS(), url: "/repo/.pnp.cjs", manifest: manifest}

	tests := []struct {
		name     string
		to       string
		from     string
		external bool
	}{
		{name: "same locator", to: "/repo/app/src/value.ts", from: "/repo/app/src/index.ts", external: false},
		{name: "fallback package", to: "/repo/fallback/src/index.ts", from: "/repo/app/src/index.ts", external: true},
		{name: "same name with different references", to: "/repo/pkg-two/src/index.ts", from: "/repo/pkg-one/src/index.ts", external: true},
		{name: "missing locator", to: "/outside/pkg/index.ts", from: "/repo/app/src/index.ts", external: false},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if actual := pnpApi.IsExternalPackagePath(test.to, test.from); actual != test.external {
				t.Fatalf("expected external=%v, got %v", test.external, actual)
			}
		})
	}
}

func TestParseSinglePackageName(t *testing.T) {
	t.Parallel()
	pnpApi := &PnpApi{}
	name, _, err := pnpApi.ParseBareIdentifier("pkg")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if name != "pkg" {
		t.Fatalf("expected name %q, got %q", "pkg", name)
	}
}

func TestParseScopedPackageName(t *testing.T) {
	t.Parallel()
	pnpApi := &PnpApi{}
	name, _, err := pnpApi.ParseBareIdentifier("@scope/pkg")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if name != "@scope/pkg" {
		t.Fatalf("expected name %q, got %q", "@scope/pkg", name)
	}
}

func TestParsePackageNameWithLongSubpath(t *testing.T) {
	t.Parallel()
	pnpApi := &PnpApi{}
	name, modulePath, err := pnpApi.ParseBareIdentifier("pkg/a/b/c/index.js")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if name != "pkg" {
		t.Fatalf("expected name %q, got %q", "pkg", name)
	}
	if modulePath != "/a/b/c/index.js" {
		t.Fatalf("expected modulePath=%q, got %q", "a/b/c/index.js", modulePath)
	}
}

func TestParseScopedPackageWithLongSubpath(t *testing.T) {
	t.Parallel()
	pnpApi := &PnpApi{}
	name, modulePath, err := pnpApi.ParseBareIdentifier("@scope/pkg/a/b/c/index.js")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if name != "@scope/pkg" {
		t.Fatalf("expected name %q, got %q", "@scope/pkg", name)
	}
	if modulePath != "/a/b/c/index.js" {
		t.Fatalf("expected modulePath=%q, got %q", "a/b/c/index.js", modulePath)
	}
}
